=== xulegaspi/lroP2/tvml22.dtd
<!ELEMENT Programacion (Fecha, Canal+)>
<!ELEMENT Fecha (#PCDATA)>
<!ELEMENT Canal (NombreCanal, Formato?, Programa+)>
<!ELEMENT NombreCanal (#PCDATA)>
<!ELEMENT Formato (#PCDATA)>
<!ELEMENT Programa (#PCDATA|NombrePrograma|Categoria|Intervalo)*>
<!ELEMENT NombrePrograma (#PCDATA)>
<!ELEMENT Categoria (#PCDATA)>
<!ELEMENT Intervalo (HoraInicio,(HoraFin | Duracion),OtraEmision?)>
<!ELEMENT HoraInicio (#PCDATA)>
<!ELEMENT HoraFin (#PCDATA)>
<!ELEMENT Duracion (#PCDATA)>
<!ELEMENT OtraEmision (Fecha, UrlTVML)>
<!ELEMENT UrlTVML (#PCDATA)>

<!ATTLIST Canal lang (en|es|fr|de|it) #REQUIRED>
<!ATTLIST Canal teletexto (si|no) "no">
<!ATTLIST Programa edadminima CDATA #REQUIRED>
<!ATTLIST Programa langs CDATA #IMPLIED>

=== xulegaspi/lroP2/tvml-error2.xml
<?xml version='1.0' encoding='ISO-8859-1' standalone='no'?>

<!DOCTYPE Programacion SYSTEM "tvml22.dtd">

<Programacion>
  <Fecha><Duracion>140</Duracion>24/12/2013</Fecha>

  <Canal lang='es' teletexto='si'>
    <NombreCanal>T5</NombreCanal>
    <Formato>16:9</Formato>
    <Programa edadminima='3' langs='es'>
	<NombrePrograma>Aqui hay Tomate</NombrePrograma>
	<Categoria>Informativos</Categoria>
	<Intervalo>
		<HoraInicio>15:00</HoraInicio>
		<HoraFin>16:00</HoraFin>
		<OtraEmision>
			<Fecha>21/12/2001</Fecha>
                         <UrlTVML>http://clave.det.uvigo.es:8080/~lroprof/tvml-21-12-2001.xml</UrlTVML>
		</OtraEmision>
	</Intervalo>
	Informese de los ultimos cotilleos del momento
    </Programa>
    
    <Programa edadminima='18' langs='en es'>
      <NombrePrograma>Night Movie</NombrePrograma>
      <Categoria>Cine</Categoria>
      La ultima peli de la noche
      <Intervalo>
        <HoraInicio>22:00</HoraInicio>
        <Duracion>140</Duracion>
      </Intervalo>
    </Programa>

    <Programa edadminima='8' langs='fr it'>
      <NombrePrograma>Futbol amateur</NombrePrograma>
      <Categoria>Deportes</Categoria>
      <Intervalo>
        <HoraInicio>09:00</HoraInicio>
        <Duracion>150</Duracion>
      </Intervalo>
      El futbol sin limites
    </Programa>

    <Programa edadminima='8' langs='fr it'>
      <NombrePrograma>Cartelera</NombrePrograma>
      <Categoria>Cine</Categoria>
      <Intervalo>
        <HoraInicio>19:00</HoraInicio>
        <Duracion>65</Duracion>
        <OtraEmision>
           <Fecha>20/12/2001</Fecha>
           <UrlTVML>http://clave.det.uvigo.es:8080/~lroprof/tvml-20-12-2001.xml</UrlTVML>
        </OtraEmision>
      </Intervalo>
      Viva el cine desde todos los puntos de vista
    </Programa>
  </Canal>

  <Canal lang='es'>
    <NombreCanal>TVE1</NombreCanal>
    <Formato>4:3</Formato>
    <Programa edadminima='3' langs='es'>
      <NombrePrograma>Club Megatrix</NombrePrograma>
      <Categoria>Infantiles</Categoria>
      <Intervalo>
        <HoraInicio>08:00</HoraInicio>
        <HoraFin>12:00</HoraFin>
      </Intervalo>
      El entretenimiento esta asegurado
    </Programa>
  </Canal>
   
  <Canal lang='de' teletexto='si'>
    <NombreCanal>TVAL1</NombreCanal>
    <Formato>16:9</Formato>
    <Programa edadminima='16' langs='es en fr it'>
	<NombrePrograma>Cine 2011</NombrePrograma>
	<Categoria>Cine</Categoria>
	<Intervalo>
		<HoraInicio>22:00</HoraInicio>
		<HoraFin>23:59</HoraFin>
	</Intervalo>
	Las peliculas y reportajes del momento
    </Programa>
    <Programa edadminima='12' langs='es en de'>
      <NombrePrograma>Informe Semanal</NombrePrograma>
      <Categoria>Informativos</Categoria>
      <Intervalo>
        <HoraInicio>20:00</HoraInicio>
        <Duracion>65</Duracion>
      </Intervalo>
      Conoce las ultimas noticias
    </Programa>
  </Canal>

  <Canal lang='it' teletexto='si'>
    <NombreCanal>TFR</NombreCanal>
    <Formato>16:9</Formato>
    <Programa edadminima='13'>
	<NombrePrograma>Deporte Toral</NombrePrograma>
	<Categoria>Deportes</Categoria>
	<Intervalo>
		<HoraInicio>17:00</HoraInicio>
		<HoraFin>19:00</HoraFin>
		<OtraEmision>
			<Fecha>21/12/2001</Fecha>
                        <UrlTVML>http://clave.det.uvigo.es:8080/~lroprof/tvml-21-12-2001.xml</UrlTVML>
		</OtraEmision>
	</Intervalo>
	Los mejores deportes y competiciones
	</Programa>
  </Canal>

  <Canal lang='it' teletexto='si'>
    <NombreCanal>TVIT</NombreCanal>
    <Formato>4:3</Formato>
    <Programa edadminima='8' langs='en de fr it'>
	<NombrePrograma>Sportmania</NombrePrograma>
	<Categoria>Deportes</Categoria>
	<Intervalo>
		<HoraInicio>11:00</HoraInicio>
		<HoraFin>14:00</HoraFin>
	</Intervalo>
	Los mejores deportes del momento
	</Programa>
  </Canal>
</Programacion>
